/*
 * generated by Xtext 2.27.0
 */
package org.tetrabox.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.tetrabox.example.MinitlRuntimeModule;
import org.tetrabox.example.MinitlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MinitlIdeSetup extends MinitlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MinitlRuntimeModule(), new MinitlIdeModule()));
	}
	
}
