/*
 * generated by Xtext 2.27.0
 */
package org.tetrabox.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMinitlScopeProvider extends DelegatingScopeProvider {
}
