/*
 * generated by Xtext 2.27.0
 */
package org.tetrabox.example.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MinitlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/tetrabox/example/parser/antlr/internal/InternalMinitl.tokens");
	}
}
