/*
 * generated by Xtext 2.9.1
 */
package org.tetrabox.example.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.tetrabox.example.ide.contentassist.antlr.internal.InternalMinitlParser;
import org.tetrabox.example.services.MinitlGrammarAccess;

public class MinitlParser extends AbstractContentAssistParser {

	@Inject
	private MinitlGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMinitlParser createParser() {
		InternalMinitlParser result = new InternalMinitlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
					put(grammarAccess.getTransformationAccess().getGroup(), "rule__Transformation__Group__0");
					put(grammarAccess.getTransformationAccess().getGroup_4(), "rule__Transformation__Group_4__0");
					put(grammarAccess.getTransformationAccess().getGroup_5(), "rule__Transformation__Group_5__0");
					put(grammarAccess.getInputMetamodelAccess().getGroup(), "rule__InputMetamodel__Group__0");
					put(grammarAccess.getMetamodelAccess().getGroup(), "rule__Metamodel__Group__0");
					put(grammarAccess.getMetamodelAccess().getGroup_1(), "rule__Metamodel__Group_1__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getObjectTemplateAccess().getGroup(), "rule__ObjectTemplate__Group__0");
					put(grammarAccess.getObjectTemplateAccess().getGroup_3(), "rule__ObjectTemplate__Group_3__0");
					put(grammarAccess.getObjectTemplateAccess().getGroup_3_1(), "rule__ObjectTemplate__Group_3_1__0");
					put(grammarAccess.getObjectTemplateAccess().getGroup_3_1_1(), "rule__ObjectTemplate__Group_3_1_1__0");
					put(grammarAccess.getBindingAccess().getGroup(), "rule__Binding__Group__0");
					put(grammarAccess.getMaybeBinaryAccess().getGroup(), "rule__MaybeBinary__Group__0");
					put(grammarAccess.getMaybeBinaryAccess().getGroup_1(), "rule__MaybeBinary__Group_1__0");
					put(grammarAccess.getMaybeFieldAccessValueAccess().getGroup(), "rule__MaybeFieldAccessValue__Group__0");
					put(grammarAccess.getMaybeFieldAccessValueAccess().getGroup_1(), "rule__MaybeFieldAccessValue__Group_1__0");
					put(grammarAccess.getPrimaryAccess().getGroup_2(), "rule__Primary__Group_2__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getTransformationAccess().getNameAssignment_1(), "rule__Transformation__NameAssignment_1");
					put(grammarAccess.getTransformationAccess().getInputMetamodelAssignment_3(), "rule__Transformation__InputMetamodelAssignment_3");
					put(grammarAccess.getTransformationAccess().getOutputMetamodelAssignment_4_1(), "rule__Transformation__OutputMetamodelAssignment_4_1");
					put(grammarAccess.getTransformationAccess().getRulesAssignment_5_0(), "rule__Transformation__RulesAssignment_5_0");
					put(grammarAccess.getTransformationAccess().getRulesAssignment_5_1(), "rule__Transformation__RulesAssignment_5_1");
					put(grammarAccess.getMetamodelAccess().getPackagesAssignment_0(), "rule__Metamodel__PackagesAssignment_0");
					put(grammarAccess.getMetamodelAccess().getPackagesAssignment_1_1(), "rule__Metamodel__PackagesAssignment_1_1");
					put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
					put(grammarAccess.getRuleAccess().getObjectTemplatesAssignment_4(), "rule__Rule__ObjectTemplatesAssignment_4");
					put(grammarAccess.getRuleAccess().getObjectTemplatesAssignment_6(), "rule__Rule__ObjectTemplatesAssignment_6");
					put(grammarAccess.getObjectTemplateAccess().getNameAssignment_0(), "rule__ObjectTemplate__NameAssignment_0");
					put(grammarAccess.getObjectTemplateAccess().getTypeAssignment_2(), "rule__ObjectTemplate__TypeAssignment_2");
					put(grammarAccess.getObjectTemplateAccess().getBindingsAssignment_3_1_0(), "rule__ObjectTemplate__BindingsAssignment_3_1_0");
					put(grammarAccess.getObjectTemplateAccess().getBindingsAssignment_3_1_1_1(), "rule__ObjectTemplate__BindingsAssignment_3_1_1_1");
					put(grammarAccess.getBindingAccess().getFeatureAssignment_0(), "rule__Binding__FeatureAssignment_0");
					put(grammarAccess.getBindingAccess().getValueAssignment_2(), "rule__Binding__ValueAssignment_2");
					put(grammarAccess.getMaybeBinaryAccess().getOperatorAssignment_1_1(), "rule__MaybeBinary__OperatorAssignment_1_1");
					put(grammarAccess.getMaybeBinaryAccess().getExpressionsAssignment_1_2(), "rule__MaybeBinary__ExpressionsAssignment_1_2");
					put(grammarAccess.getMaybeFieldAccessValueAccess().getFeatureAssignment_1_2(), "rule__MaybeFieldAccessValue__FeatureAssignment_1_2");
					put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
					put(grammarAccess.getObjectTemplateValueAccess().getObjecttemplateAssignment(), "rule__ObjectTemplateValue__ObjecttemplateAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalMinitlParser typedParser = (InternalMinitlParser) parser;
			typedParser.entryRuleTransformation();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MinitlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MinitlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
