/*
 * generated by Xtext 2.9.1
 */
package org.tetrabox.example.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.tetrabox.example.services.MinitlGrammarAccess;

@SuppressWarnings("all")
public class MinitlSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MinitlGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ObjectTemplate_SemicolonKeyword_3_2_q;
	protected AbstractElementAlias match_ObjectTemplate___LeftCurlyBracketKeyword_3_0_SemicolonKeyword_3_2_q_RightCurlyBracketKeyword_3_3__q;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_2_0_a;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_2_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MinitlGrammarAccess) access;
		match_ObjectTemplate_SemicolonKeyword_3_2_q = new TokenAlias(false, true, grammarAccess.getObjectTemplateAccess().getSemicolonKeyword_3_2());
		match_ObjectTemplate___LeftCurlyBracketKeyword_3_0_SemicolonKeyword_3_2_q_RightCurlyBracketKeyword_3_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getObjectTemplateAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, true, grammarAccess.getObjectTemplateAccess().getSemicolonKeyword_3_2()), new TokenAlias(false, false, grammarAccess.getObjectTemplateAccess().getRightCurlyBracketKeyword_3_3()));
		match_Primary_LeftParenthesisKeyword_2_0_a = new TokenAlias(true, true, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_2_0());
		match_Primary_LeftParenthesisKeyword_2_0_p = new TokenAlias(true, false, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_2_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ObjectTemplate_SemicolonKeyword_3_2_q.equals(syntax))
				emit_ObjectTemplate_SemicolonKeyword_3_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ObjectTemplate___LeftCurlyBracketKeyword_3_0_SemicolonKeyword_3_2_q_RightCurlyBracketKeyword_3_3__q.equals(syntax))
				emit_ObjectTemplate___LeftCurlyBracketKeyword_3_0_SemicolonKeyword_3_2_q_RightCurlyBracketKeyword_3_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Primary_LeftParenthesisKeyword_2_0_a.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_2_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Primary_LeftParenthesisKeyword_2_0_p.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_2_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     bindings+=Binding (ambiguity) '}' (rule end)
	 */
	protected void emit_ObjectTemplate_SemicolonKeyword_3_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' ';'? '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=[EClass|FQN] (ambiguity) (rule end)
	 */
	protected void emit_ObjectTemplate___LeftCurlyBracketKeyword_3_0_SemicolonKeyword_3_2_q_RightCurlyBracketKeyword_3_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) objecttemplate=[ObjectTemplate|ID]
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {BinaryExpression.expressions+=}
	 *     (rule start) (ambiguity) {FieldAccessValue.object=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_2_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {BinaryExpression.expressions+=}
	 *     (rule start) (ambiguity) {FieldAccessValue.object=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_2_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
