/*
 * generated by Xtext 2.9.1
 */
package org.tetrabox.example.tests

import com.google.inject.Inject
import minitl.Transformation
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MinitlInjectorProvider)
class MinitlParsingTest{

	@Inject
	ParseHelper<Transformation> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
