/**
 * generated by Xtext 2.27.0
 */
package org.tetrabox.example.minitl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tetrabox.example.minitl.BinaryExpression#getExpressions <em>Expressions</em>}</li>
 *   <li>{@link org.tetrabox.example.minitl.BinaryExpression#getOperator <em>Operator</em>}</li>
 * </ul>
 *
 * @see org.tetrabox.example.minitl.MinitlPackage#getBinaryExpression()
 * @model
 * @generated
 */
public interface BinaryExpression extends Value
{
  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.tetrabox.example.minitl.Value}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see org.tetrabox.example.minitl.MinitlPackage#getBinaryExpression_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<Value> getExpressions();

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.tetrabox.example.minitl.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.tetrabox.example.minitl.Operator
   * @see #setOperator(Operator)
   * @see org.tetrabox.example.minitl.MinitlPackage#getBinaryExpression_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link org.tetrabox.example.minitl.BinaryExpression#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.tetrabox.example.minitl.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

} // BinaryExpression
