/**
 * generated by Xtext 2.27.0
 */
package org.tetrabox.example.minitl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Template Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tetrabox.example.minitl.ObjectTemplateValue#getObjecttemplate <em>Objecttemplate</em>}</li>
 * </ul>
 *
 * @see org.tetrabox.example.minitl.MinitlPackage#getObjectTemplateValue()
 * @model
 * @generated
 */
public interface ObjectTemplateValue extends Value
{
  /**
   * Returns the value of the '<em><b>Objecttemplate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objecttemplate</em>' reference.
   * @see #setObjecttemplate(ObjectTemplate)
   * @see org.tetrabox.example.minitl.MinitlPackage#getObjectTemplateValue_Objecttemplate()
   * @model
   * @generated
   */
  ObjectTemplate getObjecttemplate();

  /**
   * Sets the value of the '{@link org.tetrabox.example.minitl.ObjectTemplateValue#getObjecttemplate <em>Objecttemplate</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objecttemplate</em>' reference.
   * @see #getObjecttemplate()
   * @generated
   */
  void setObjecttemplate(ObjectTemplate value);

} // ObjectTemplateValue
