/**
 * generated by Xtext 2.27.0
 */
package org.tetrabox.example.minitl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.tetrabox.example.minitl.MinitlPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
} // Value
