/*
 * generated by Xtext 2.9.1
 */
package org.tetrabox.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.tetrabox.example.minitl.dynamic.tcs.ui.internal.TcsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MinitlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TcsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TcsActivator.getInstance().getInjector(TcsActivator.ORG_TETRABOX_EXAMPLE_MINITL);
	}
	
}
