/*
 * generated by Xtext 2.27.0
 */
package org.tetrabox.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.tetrabox.example.minitl.ui.internal.MinitlActivator;

public class MinitlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MinitlActivator.getInstance().getInjector("org.tetrabox.example.Minitl");
	}

}
