/*
 * generated by Xtext 2.9.1
 */
package org.tetrabox.example


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MinitlRuntimeModule extends AbstractMinitlRuntimeModule {
}
